# Спавнер АВД
- type: entity
  id: SpawnPointIAA
  parent: SpawnPointJobBase
  name: АВД
  suffix: AdvRoles, AdvMapping
  components:
  - type: SpawnPoint
    job_id: IAA # Corvax-IAA: Lawyer replaced with IAA
  - type: Sprite
    layers:
      - state: green
      - state: lawyer