#Created: raidgo Transferred:  depresh
- type: entity
  name: Блюспейс Кристалл
  parent: BaseItem
  id: CentCommCrystal
  suffix: 20 БК
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/Uplinks/telecrystal.rsi
    state: telecrystal
  - type: Item
    sprite: Adventure/Roles/SpecialForces/Uplinks/telecrystal.rsi
    size: Tiny
  - type: Stack
    count: 20
    stackType: CentCommCrystal
  - type: StaticPrice
    price: 0
  - type: StackPrice
    price: 200
  - type: Currency
    price:
      CentCommCrystal: 1

- type: entity
  parent: CentCommCrystal
  id: CentCommCrystal1
  name: Блюспейс Кристалл
  suffix: 1 БК
  components:
  - type: Stack
    count: 1

- type: currency
  id: CentCommCrystal
  displayName: Блюспейс Кристаллы
  cash:
    1: CentCommCrystal1
  canWithdraw: true
