# Аплинк солдата
- type: entity
  parent: BaseItem
  id: ERTuplink
  name: Терминал ОБР
  suffix: Adventure
  description: Терминал который использует ОБР в специальных операциях.
  components:
  - type: Item
    size: Small
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: ActivatableUI
    key: enum.StoreUiKey.Key
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
    layers:
    - state: ERT
  - type: Appearance
  - type: StaticPrice
    price: 100
  - type: Store
    categories:
      - ERTweapons
      - ERTammo
      - ERTmore
      - ERTbombs
      - ERTmedicine
    currencyWhitelist:
      - CentCommCrystal
    balance:
      CentCommCrystal: 30

# Аплинк лидера
- type: entity
  parent: BaseItem
  id: ERTuplinkleader
  name: Терминал ОБР лидера
  suffix: Adventure
  description: Терминал который используют ОБР лидеры в специальных операциях.
  components:
  - type: Item
    size: Small
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: ActivatableUI
    key: enum.StoreUiKey.Key
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
    layers:
    - state: ERT_L
  - type: Appearance
  - type: StaticPrice
    price: 100
  - type: Store
    categories:
      - ERTweapons
      - ERTammo
      - ERTmore
      - ERTmedic
      - ERTbombs
      - ERTmedicine
      - ERTengi
      - ERTleader
    currencyWhitelist:
      - CentCommCrystal
    balance:
      CentCommCrystal: 40

# Аплинк медика
- type: entity
  parent: BaseItem
  id: ERTuplinkMED
  name: Терминал ОБР медика
  suffix: Adventure
  description: Терминал который использует ОБР медики в специальных операциях.
  components:
  - type: Item
    size: Small
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: ActivatableUI
    key: enum.StoreUiKey.Key
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
    layers:
    - state: ERT
  - type: Appearance
  - type: StaticPrice
    price: 100
  - type: Store
    categories:
      - ERTweapons
      - ERTammo
      - ERTmore
      - ERTbombs
      - ERTmedicine
      - ERTmedic
    currencyWhitelist:
      - CentCommCrystal
    balance:
      CentCommCrystal: 35

# Аплинк инженера
- type: entity
  parent: BaseItem
  id: ERTuplinkENGI
  name: Терминал ОБР инженера
  suffix: Adventure
  description: Терминал который используют ОБР инженеры в специальных операциях.
  components:
  - type: Item
    size: Small
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: ActivatableUI
    key: enum.StoreUiKey.Key
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
    layers:
    - state: ERT
  - type: Appearance
  - type: StaticPrice
    price: 100
  - type: Store
    categories:
      - ERTweapons
      - ERTammo
      - ERTmore
      - ERTbombs
      - ERTmedicine
      - ERTengi
    currencyWhitelist:
      - CentCommCrystal
    balance:
      CentCommCrystal: 35

# Аплинк уборщика
- type: entity
  parent: BaseItem
  id: ERTuplinkojanitor
  name: Терминал ОБР уборщика
  suffix: Adventure
  description: Терминал который используют ОБР уборщики в специальных операциях.
  components:
  - type: Item
    size: Small
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: ActivatableUI
    key: enum.StoreUiKey.Key
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
    layers:
    - state: ERT
  - type: Appearance
  - type: StaticPrice
    price: 100
  - type: Store
    categories:
      - ERTweapons
      - ERTammo
      - ERTmore
      - ERTbombs
      - ERTmedicine
      - ERTjanitor
    currencyWhitelist:
      - CentCommCrystal
    balance:
      CentCommCrystal: 35

# Аплинк священника
- type: entity
  parent: BaseItem
  id: ERTuplinklight
  name: Терминал ОБР священника
  suffix: Adventure
  description: Терминал который используют ОБР священники в специальных операциях.
  components:
  - type: Item
    size: Small
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: ActivatableUI
    key: enum.StoreUiKey.Key
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
    layers:
    - state: ERT
  - type: Appearance
  - type: StaticPrice
    price: 100
  - type: Store
    categories:
      - ERTweapons
      - ERTammo
      - ERTmore
      - ERTbombs
      - ERTmedicine
      - ERTlight
    currencyWhitelist:
      - CentCommCrystal
    balance:
      CentCommCrystal: 35

# Предметы аплинка - Оружие
- type: storeCategory
  id: ERTweapons
  name: Оружие

- type: listing
  id: WeaponPistolMk58ERT
  productEntity: WeaponPistolMk58
  cost:
    CentCommCrystal: 2
  categories:
  - ERTweapons

- type: listing
  id: WeaponDisablerERTs
  productEntity: WeaponDisabler
  cost:
    CentCommCrystal: 3
  categories:
  - ERTweapons

- type: listing
  id: WeaponPulsePistolERT
  productEntity: WeaponPulsePistol
  cost:
    CentCommCrystal: 7
  categories:
  - ERTweapons

- type: listing
  id: WeaponPistolN1984ERT
  productEntity: WeaponPistolN1984
  cost:
    CentCommCrystal: 7
  categories:
  - ERTweapons

- type: listing
  id: WeaponSubMachineGunWt550ERTs
  productEntity: WeaponSubMachineGunWt550
  cost:
    CentCommCrystal: 15
  categories:
  - ERTweapons

- type: listing
  id: WeaponRifleLecterERT
  productEntity: WeaponRifleLecter
  cost:
    CentCommCrystal: 15
  categories:
  - ERTweapons

- type: listing
  id: WeaponRifleM90GrenadeLauncherERT
  productEntity: WeaponRifleM90GrenadeLauncher
  cost:
    CentCommCrystal: 15
  categories:
  - ERTweapons

- type: listing
  id: WeaponShotgunEnforcerERT
  productEntity: WeaponShotgunEnforcer
  cost:
    CentCommCrystal: 15
  categories:
  - ERTweapons

- type: listing
  id: WeaponPulseCarbineERT
  productEntity: WeaponPulseCarbine
  cost:
    CentCommCrystal: 20
  categories:
  - ERTweapons

- type: listing
  id: WeaponTaserERT
  productEntity: WeaponTaser
  cost:
    CentCommCrystal: 20
  categories:
  - ERTweapons

- type: listing
  id: WeaponAdvancedLaserERT
  productEntity: WeaponAdvancedLaser
  cost:
    CentCommCrystal: 21
  categories:
  - ERTweapons

# Предметы аплинка - Боеприпасы
- type: storeCategory
  id: ERTammo
  name: Боеприпасы

- type: listing
  id: MagazinePistolERT
  productEntity: MagazinePistol
  description: Магазин калибра 35 авто. Подходящий для простых пистолетов
  cost:
    CentCommCrystal: 1
  categories:
  - ERTammo

- type: listing
  id: MagazineMagnumERT
  productEntity: MagazineMagnum
  description: Магазин калибра 45 магнум. Подходящий для тяжёлых пистолетов или револьверов.
  cost:
    CentCommCrystal: 2
  categories:
  - ERTammo

- type: listing
  id: MagazineRifleERT
  productEntity: MagazineRifle
  description: Магазин калибра 20. Винтовочный подходящий для автоматов.
  cost:
    CentCommCrystal: 2
  categories:
  - ERTammo

- type: listing
  id: MagazinePistolSubMachineGunTopMountedERT
  productEntity: MagazinePistolSubMachineGunTopMounted
  description: Надствольный магазин калибра 35 авто. Подходящий для пистолетов-пулемётов.
  cost:
    CentCommCrystal: 2
  categories:
  - ERTammo

- type: listing
  id: MagazineBoxPistolERT
  productEntity: MagazineBoxPistol
  description: Коробка калибра 35 авто. Подходящий для простых пистолетов.
  cost:
    CentCommCrystal: 4
  categories:
  - ERTammo

- type: listing
  id: MagazineBoxMagnumERT
  productEntity: MagazineBoxMagnum
  description: Коробка калибра 45 магнум. Подходящий для тяжёлых пистолетов или револьверов.
  cost:
    CentCommCrystal: 8
  categories:
  - ERTammo

- type: listing
  id: MagazineBoxRifleERT
  productEntity: MagazineBoxRifle
  description: Коробка калибра 20. Винтовочный подходящий для автоматов.
  cost:
    CentCommCrystal: 3
  categories:
  - ERTammo

- type: listing
  id: MagazineShotgunERT
  productEntity: MagazineShotgun
  description: Барабн калибра 50. Подходящий дробовиков.
  cost:
    CentCommCrystal: 3
  categories:
  - ERTammo

- type: listing
  id: MagazineBoxMagnumAPERT
  productEntity: MagazineBoxMagnumAP
  description: Коробка патронов 45 магнум бронебойные . Подходящий для тяжёлых пистолетов или револьверов.
  cost:
    CentCommCrystal: 7
  categories:
  - ERTammo

# Предметы аплинка - Боеприпасы

# Предметы аплинка - Разное
- type: storeCategory
  id: ERTmore
  name: Разное

- type: listing
  id: MindShieldImplanterERT
  productEntity: MindShieldImplanter
  cost:
    CentCommCrystal: 1
  categories:
  - ERTmore

- type: listing
  id: ClothingShoesBootsMagERT
  productEntity: ClothingShoesBootsMag
  cost:
    CentCommCrystal: 3
  categories:
  - ERTmore

- type: listing
  id: PinpointerNuclearERT
  productEntity: PinpointerNuclear
  cost:
    CentCommCrystal: 1
  categories:
  - ERTmore

- type: listing
  id: JetpackBlueFilledERT
  productEntity: JetpackBlueFilled
  cost:
    CentCommCrystal: 3
  categories:
  - ERTmore

- type: listing
  id: ClothingOuterHardsuitERTSecurityERT
  productEntity: ClothingOuterHardsuitERTSecurity
  cost:
    CentCommCrystal: 5
  categories:
  - ERTmore

- type: listing
  id: JawsOfLifeERT
  productEntity: JawsOfLife
  cost:
    CentCommCrystal: 5
  categories:
  - ERTmore

# /Предметы аплинка - Разное

# Предметы аплинка - Взрывчатка
- type: storeCategory
  id: ERTbombs
  name: Взрывчатка

- type: listing
  id: GrenadeFlashBangERT
  productEntity: GrenadeFlashBang
  cost:
    CentCommCrystal: 1
  categories:
  - ERTbombs

- type: listing
  id: TearGasGrenadeERT
  productEntity: TearGasGrenade
  cost:
    CentCommCrystal: 2
  categories:
  - ERTbombs

- type: listing
  id: GrenadeStingerERT
  productEntity: GrenadeStinger
  cost:
    CentCommCrystal: 2
  categories:
  - ERTbombs

- type: listing
  id: ClusterBangFullERT
  productEntity: ClusterBangFull
  cost:
    CentCommCrystal: 2
  categories:
  - ERTbombs

- type: listing
  id: GrenadeIncendiaryERT
  productEntity: GrenadeIncendiary
  cost:
    CentCommCrystal: 3
  categories:
  - ERTbombs

- type: listing
  id: C4ERT
  productEntity: C4
  cost:
    CentCommCrystal: 3
  categories:
  - ERTbombs

- type: listing
  id: ClusterGrenadeERT
  productEntity: ClusterGrenade
  cost:
    CentCommCrystal: 7
  categories:
  - ERTbombs
# /Предметы аплинка - Взрывчатка

# Предметы аплинка - Медицина
- type: listing
  id: BrutepackERT
  productEntity: Brutepack
  cost:
    CentCommCrystal: 1
  categories:
  - ERTmedicine

- type: storeCategory
  id: ERTmedicine
  name: Медицина

- type: listing
  id: OintmentERT
  productEntity: Ointment
  cost:
    CentCommCrystal: 1
  categories:
  - ERTmedicine

- type: listing
  id: GauzeERT
  productEntity: Gauze
  cost:
    CentCommCrystal: 1
  categories:
  - ERTmedicine

- type: listing
  id: BloodpackERT
  productEntity: Bloodpack
  cost:
    CentCommCrystal: 1
  categories:
  - ERTmedicine

- type: listing
  id: HandheldHealthAnalyzerERT
  productEntity: HandheldHealthAnalyzer
  cost:
    CentCommCrystal: 2
  categories:
  - ERTmedicine

- type: listing
  id: MedkitFilledERT
  productEntity: MedkitFilled
  cost:
    CentCommCrystal: 3
  categories:
  - ERTmedicine

# /Предметы аплинка - Медицина

# Предметы аплинка медика
- type: storeCategory
  id: ERTmedic
  name: ОБР медик

- type: listing
  id: DefibrillatorERT
  productEntity: Defibrillator
  cost:
    CentCommCrystal: 1
  categories:
  - ERTmedic

- type: listing
  id: MaterialBiomassERT
  productEntity: MaterialBiomass
  cost:
    CentCommCrystal: 2
  categories:
  - ERTmedic

- type: listing
  id: MedicatedSutureERT
  productEntity: MedicatedSuture
  cost:
    CentCommCrystal: 3
  categories:
  - ERTmedic

- type: listing
  id: RegenerativeMeshERT
  productEntity: RegenerativeMesh
  cost:
    CentCommCrystal: 3
  categories:
  - ERTmedic

- type: listing
  id: OmnizineChemistryBottleERT
  productEntity: OmnizineChemistryBottle
  cost:
    CentCommCrystal: 4
  categories:
  - ERTmedic
  conditions:
    - !type:ListingLimitedStockCondition
     stock: 1

- type: listing
  id: HyposprayERTbuy
  productEntity: HyposprayERT
  cost:
    CentCommCrystal: 5
  categories:
  - ERTmedic
  conditions:
    - !type:ListingLimitedStockCondition
     stock: 1

- type: listing
  id: MedkitAdvancedFilledERT
  productEntity: MedkitAdvancedFilled
  cost:
    CentCommCrystal: 6
  categories:
  - ERTmedic

- type: listing
  id: MedkitCombatFilledERT
  productEntity: MedkitCombatFilled
  cost:
    CentCommCrystal: 7
  categories:
  - ERTmedic
  conditions:
    - !type:ListingLimitedStockCondition
     stock: 1

- type: listing
  id: InjectorMediumNanitsERT
  productEntity: InjectorMediumNanits
  cost:
    CentCommCrystal: 15
  categories:
  - ERTmedic
  conditions:
    - !type:ListingLimitedStockCondition
     stock: 1

# /Предметы аплинка медика

# Предметы аплинка инженера
- type: storeCategory
  id: ERTengi
  name: ОБР инженер

- type: listing
  id: SheetSteelERT
  productEntity: SheetSteel
  cost:
    CentCommCrystal: 1
  categories:
  - ERTengi

- type: listing
  id: SheetGlassERT
  productEntity: SheetGlass
  cost:
    CentCommCrystal: 1
  categories:
  - ERTengi

- type: listing
  id: SheetPlasticERT
  productEntity: SheetPlastic
  cost:
    CentCommCrystal: 1
  categories:
  - ERTengi

- type: listing
  id: CableApcStackERT
  productEntity: CableApcStack
  cost:
    CentCommCrystal: 1
  categories:
  - ERTengi

- type: listing
  id: CableMVStackERT
  productEntity: CableMVStack
  cost:
    CentCommCrystal: 1
  categories:
  - ERTengi

- type: listing
  id: CableHVStackERT
  productEntity: CableHVStack
  cost:
    CentCommCrystal: 1
  categories:
  - ERTengi

- type: listing
  id: MetalFoamGrenadeERT
  productEntity: MetalFoamGrenade
  cost:
    CentCommCrystal: 1
  categories:
  - ERTengi

- type: listing
  id: SheetPlasteelERT
  productEntity: SheetPlasteel
  cost:
    CentCommCrystal: 1
  categories:
  - ERTengi

- type: listing
  id: RCDRechargingERT
  productEntity: RCDRecharging
  cost:
    CentCommCrystal: 4
  categories:
  - ERTengi
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1
# /Предметы аплинка инженера

# Предметы аплинка лидера
- type: storeCategory
  id: ERTleader
  name: ОБР лидер

- type: listing
  id: WeaponPlasmaSniperERTs
  productEntity: WeaponPlasmaSniper
  cost:
    CentCommCrystal: 18
  categories:
  - ERTleader

- type: listing
  id: WeaponSniperHristovERT
  productEntity: WeaponSniperHristov
  cost:
    CentCommCrystal: 14
  categories:
  - ERTleader

- type: listing
  id: MagazineBoxAntiMaterielERT
  description: Коробка снайперских патронов совместимых со снайперской винтовкой "Христов"
  productEntity: MagazineBoxAntiMateriel
  cost:
    CentCommCrystal: 3
  categories:
  - ERTleader

- type: listing
  id: PlushieSharki_MakcuERT
  productEntity: PlushieSharki_Makcu
  cost:
    CentCommCrystal: 1
  categories:
  - ERTleader
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1

- type: listing
  id: ClothingShoesBootsMagAdvtwoERT
  productEntity: ClothingShoesBootsMagAdv
  cost:
    CentCommCrystal: 4
  categories:
  - ERTleader
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1
# /Предметы аплинка лидера

# Предметы аплинка уборщика
- type: storeCategory
  id: ERTjanitor
  name: ОБР уборщик

- type: listing
  id: BoxBodyBagERT
  productEntity: BoxBodyBag
  cost:
    CentCommCrystal: 4
  categories:
  - ERTjanitor

- type: listing
  id: MobCleanBotERT
  productEntity: MobCleanBot
  cost:
    CentCommCrystal: 3
  categories:
  - ERTjanitor

- type: listing
  id: AdvMopItemERT
  productEntity: AdvMopItem
  cost:
    CentCommCrystal: 5
  categories:
  - ERTjanitor

- type: listing
  id: TrashBagBlueERT
  productEntity: TrashBagBlue
  description: Позволяет убирать даже самые грязные места.
  cost:
    CentCommCrystal: 2
  categories:
  - ERTjanitor

- type: listing
  id: CleanerGrenadeERT
  productEntity: CleanerGrenade
  cost:
    CentCommCrystal: 1
  categories:
  - ERTjanitor

- type: listing
  id: ClothingShoesBootsMagAdvERT
  productEntity: ClothingShoesBootsMagAdv
  cost:
    CentCommCrystal: 5
  categories:
  - ERTjanitor
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1
# /Предметы аплинка уборщика

# Предметы аплинка священника
- type: storeCategory
  id: ERTlight
  name: ОБР священник

- type: listing
  id: AltarNanotrasenERT
  productEntity: AltarNanotrasen
  cost:
    CentCommCrystal: 4
  categories:
  - ERTlight

- type: listing
  id: FoodBakedBunHotXERT
  productEntity: FoodBakedBunHotX
  cost:
    CentCommCrystal: 2
  categories:
  - ERTlight

- type: listing
  id: Bible
  productEntity: Bible
  cost:
    CentCommCrystal: 2
  categories:
  - ERTlight

- type: listing
  id: BoxCandleERT
  productEntity: BoxCandle
  cost:
    CentCommCrystal: 3
  categories:
  - ERTlight

- type: listing
  id: BoxBodyBagERTEP
  productEntity: BoxBodyBag
  cost:
    CentCommCrystal: 3
  categories:
  - ERTlight

- type: listing
  id: LanternERT
  productEntity: Lantern
  cost:
    CentCommCrystal: 1
  categories:
  - ERTlight

- type: listing
  id: LighterERT
  productEntity: Lighter
  cost:
    CentCommCrystal: 1
  categories:
  - ERTlight
# /Предметы аплинка священника
# /Дебаг аплинк
- type: entity
  parent: BaseItem
  id: ERTuplinkabuse
  name: Терминал ОБР акулки
  suffix: Adventure, DEBUG
  description: Терминал который используют ОБР акулки? в специальных операциях.
  components:
  - type: Item
    size: Small
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: ActivatableUI
    key: enum.StoreUiKey.Key
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/Uplinks/communication.rsi
    layers:
    - state: ERT
  - type: Appearance
  - type: StaticPrice
    price: 100
  - type: Store
    categories:
      - ERTweapons
      - ERTammo
      - ERTmore
      - ERTbombs
      - ERTmedic
      - ERTmedicine
      - ERTlight
      - ERTjanitor
      - ERTleader
      - ERTengi
    currencyWhitelist:
      - CentCommCrystal
    balance:
      CentCommCrystal: 9999
