#Скафандр ОСЩ
- type: entity
  parent: ClothingHeadHardsuitWithLightBase
  id: ClothingHeadHelmetHardsuitBlueshield
  name: Шлем скафандра офицера синего щита
  description: Укреплённый шлем с новой системой NT-HUD, которая не работает.
  components:
  - type: BreathMask
  - type: Sprite
    sprite: Adventure/Roles/blueshield/Clothing/OUTERCLOTHING/Hardsuit/Head/Blueshield.rsi
  - type: Clothing
    sprite: Adventure/Roles/blueshield/Clothing/OUTERCLOTHING/Hardsuit/Head/Blueshield.rsi
  - type: PointLight
    color: cyan
  - type: PressureProtection
    highPressureMultiplier: 0.45
    lowPressureMultiplier: 1000
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.9
        Slash: 0.9
        Piercing: 0.9
        Heat: 0.9

- type: entity
  parent: ClothingOuterHardsuitSecurity
  id: ClothingOuterHardsuitBlueshield
  name: Скафандр офицера синего щита
  description: Специальный костюм защищающий от внешний угроз. С дополнительным слоем брони.
  components:
  - type: Sprite
    sprite: Adventure/Roles/blueshield/Clothing/OUTERCLOTHING/Hardsuit/Suit/Blueshield.rsi
  - type: Clothing
    sprite: Adventure/Roles/blueshield/Clothing/OUTERCLOTHING/Hardsuit/Suit/Blueshield.rsi
  - type: PressureProtection
    highPressureMultiplier: 0.45
    lowPressureMultiplier: 1000
  - type: ExplosionResistance
    damageCoefficient: 0.6
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.6
        Slash: 0.5
        Piercing: 0.5
        Radiation: 0.5
        Caustic: 0.6
  - type: ClothingSpeedModifier
    walkModifier: 0.8
    sprintModifier: 0.8
  - type: HeldSpeedModifier
  - type: ToggleableClothing
    clothingPrototype: ClothingHeadHelmetHardsuitBlueshield

#Броня
- type: entity
  parent: ClothingOuterArmorBasic
  id: ClothingOuterArmorBlueshield
  name: Улучшенный бронежилет
  description: Бронежилет укреплённый керамическими пластинами. Несколько мешает движениям, но многократно увеличивает шансы на выживание.
  components:
  - type: Sprite
    sprite: Adventure/Roles/blueshield/Clothing/OUTERCLOTHING/armor.rsi
  - type: Clothing
    sprite: Adventure/Roles/blueshield/Clothing/OUTERCLOTHING/armor.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.5
        Slash: 0.5
        Piercing: 0.4
        Heat: 0.5
  - type: ExplosionResistance
    damageCoefficient: 0.80

#Бронекуртка
- type: entity
  parent: ClothingOuterCoatHoSTrench
  id: ClothingOuterArmorCoatBlueshield
  name: Бронекуртка офицера синего щита
  description: Шинель, усиленная специальным сплавом для дополнительной защиты и придания стиля тем, у кого внушительный вид.
  components:
    - type: Sprite
      sprite: Adventure/Roles/blueshield/Clothing/OUTERCLOTHING/BSarmoredcoat.rsi
    - type: Clothing
      sprite: Adventure/Roles/blueshield/Clothing/OUTERCLOTHING/BSarmoredcoat.rsi
    - type: Armor
      modifiers:
        coefficients:
          Blunt: 0.7
          Slash: 0.7
          Piercing: 0.4
          Heat: 0.7

- type: entity
  parent: ClothingOuterArmorCoatBlueshield
  id: ClothingOuterArmorCoatBlueshieldParade
  name: Парадная бронекуртка офицера синего щита
  components:
    - type: Sprite
      sprite: Adventure/Roles/blueshield/Clothing/OUTERCLOTHING/BSformaljacket.rsi
    - type: Clothing
      sprite: Adventure/Roles/blueshield/Clothing/OUTERCLOTHING/BSformaljacket.rsi