- type: entity
  parent: ClothingOuterArmorBasic
  id: BlueShieldArmoredTrench
  name: Укреплённый тренч офицера "синий щит"
  description: Тренч из самых лучших синтетических материалов и с прочными вставками из керамических пластин. Не мешает движениям, но защищает на ура
  components:
  - type: Sprite
    sprite: Adventure/Roles/blueshield/Clothing/OUTERCLOTHING/Trench.rsi
  - type: Clothing
    sprite: Adventure/Roles/blueshield/Clothing/OUTERCLOTHING/Trench.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.60
        Slash: 0.60
        Piercing: 0.50
        Heat: 0.70
  - type: ExplosionResistance
    damageCoefficient: 0.75