- type: entity
  parent: BaseItem
  id: BSuplink
  name: Терминал снаряжения ОСЩ
  suffix: Adventure, Old
  description: Терминал который использует офицеры синего щита для покупки снаряжения.
  components:
  - type: Item
    size: Small
    sprite: Adventure/Roles/blueshield/Terminal.rsi
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: ActivatableUI
    key: enum.StoreUiKey.Key
  - type: Sprite
    sprite: Adventure/Roles/blueshield/Terminal.rsi
    layers:
    - state: old-radio
  - type: Appearance
  - type: StaticPrice
    price: 100
  - type: Store
    categories:
      - BSweapons
      - BSammo
      - BSnanit
      - BSequip
      - BSsouz
#      - BSBoom
      - BSimp
      - BSmoremore
    currencyWhitelist:
      - CentCommCrystal
    balance:
      CentCommCrystal: 20

- type: storeCategory
  id: BSweapons
  name: Вооружение

- type: storeCategory
  id: BSmoremore
  name: Безделушки

- type: storeCategory
  id: BSBoom
  name: Взрывчатка

- type: storeCategory
  id: BSammo
  name: Боеприпасы

- type: storeCategory
  id: BSnanit
  name: Химикаты

- type: storeCategory
  id: BSmed
  name: Медикаменты

- type: storeCategory
  id: BSmore
  name: Разное

- type: storeCategory
  id: BSimp
  name: Импланты

- type: storeCategory
  id: BSequip
  name: Экипировка

- type: storeCategory
  id: BSsouz
  name: Союзники

- type: storeCategory
  id: BSengi
  name: Инструменты

- type: listing
  id: ClothingBeltSheathBSshop
  name: Офицерская сабля
  description: Личная церемониальная сабля для офицера синего щита.
  productEntity: ClothingBeltSheathBS
  cost:
    CentCommCrystal: 8
  categories:
  - BSweapons
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1

- type: listing
  id: WeaponPistolMk58Shop
  description: Небольшой маломощный пистолет. Производится на фабриках Nanotrasen.
  productEntity: WeaponPistolMk58
  cost:
    CentCommCrystal: 2
  categories:
  - BSweapons

- type: listing
  id: WeaponPistolN1984BS
  productEntity: WeaponPistolN1984
  cost:
    CentCommCrystal: 4
  categories:
  - BSweapons

- type: listing
  id: energygunShop
  productEntity: WeaponX2DualphaseEnergyLaserGun
  cost:
    CentCommCrystal: 6
  categories:
  - BSweapons
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1

#- type: listing
#  id: WeaponTaserShop
#  description: Позволяет ошеломить даже самого сильного врага.
#  productEntity: WeaponTaser
#  cost:
#    CentCommCrystal: 10
#  categories:
#  - BSweapons
#  conditions:
#  - !type:ListingLimitedStockCondition
#   stock: 1

- type: listing
  id: MagazinePistolShop
  description: Пистолетный магазин. Совместим с MK 58.
  productEntity: MagazinePistol
  cost:
    CentCommCrystal: 1
  categories:
  - BSammo

- type: listing
  id: MagazineMagnumshop
  description: Магазин дорогих патрон. Совсестим с N1984.
  productEntity: MagazineMagnum
  cost:
    CentCommCrystal: 3
  categories:
  - BSammo

- type: listing
  id: GrenadeFlashBangShop
  description: Стандартная светошумовая граната. Перед использованием стоит одеть экипировку с защитой от вспышек.
  productEntity: GrenadeFlashBang
  cost:
    CentCommCrystal: 1
  categories:
  - BSBoom

- type: listing
  id: SmokeGrenadeShop
  description: Граната выпускающая огромное количество слезоточивого газа. подходит для сдерживания, или пыток.
  productEntity: TearGasGrenade
  cost:
    CentCommCrystal: 1
  categories:
  - BSBoom

- type: listing
  id: EmpGrenadeShop
  description: Поможет остановить сломанного киборга.
  productEntity: EmpGrenade
  cost:
    CentCommCrystal: 2
  categories:
  - BSBoom

- type: listing
  id: ExGrenadeShop
  description: Обычная взрывная граната.
  productEntity: ExGrenade
  cost:
    CentCommCrystal: 3
  categories:
  - BSBoom

#- type: listing
#  id: ClothingBeltHolsterShop
#  description: Глубокая плечевая кобура, поможет вместить оружие и патроны.
#  productEntity: ClothingBeltHolster
#  cost:
#    CentCommCrystal: 1
#  categories:
#  - BSequip

- type: listing
  id: ClothingBeltMilitaryWebbingBlueshieldShop
  description: Удобный РПС синего щита
  productEntity: ClothingBeltMilitaryWebbingBlueshield
  cost:
    CentCommCrystal: 1
  categories:
  - BSequip

- type: listing
  id: ClothingShoesBootsMagSciShop
  description: Предотвращяют подскальзывания и позволяют удобно передвигаться в условиях невесомости.
  productEntity: ClothingShoesBootsMagSci
  cost:
    CentCommCrystal: 2
  categories:
  - BSequip

- type: listing
  id: JetpackBlueFilledShop
  description: Синий джетпак. Позволяет летать в космосе. Топливо входит в комплект.
  productEntity: JetpackBlueFilled
  cost:
    CentCommCrystal: 2
  categories:
  - BSequip

- type: listing
  id: ClothingMaskGasSwatShop
  description: Удобный противогаз дающий небольшую защиту.
  productEntity: ClothingMaskGasSwat
  cost:
    CentCommCrystal: 1
  categories:
  - BSequip

- type: listing
  id: ClothingOuterArmorBlueshieldShop
  description: Бронежилет укреплённый керамическими пластинами. Несколько мешает движениям, но многократно увеличивает шансы на выживание.
  productEntity: ClothingOuterArmorBlueshield
  cost:
    CentCommCrystal: 1
  categories:
  - BSequip
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1

- type: listing
  id: BlueShieldArmoredTrenchShop
  description: Тренч из самых лучших синтетических материалов и с прочными вставками из керамических пластин. Не мешает движениям, но защищает на ура.
  productEntity: BlueShieldArmoredTrench
  cost:
    CentCommCrystal: 2
  categories:
  - BSequip
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1

#- type: listing
#  id: WeaponSyringeGunShop
#  description: Шприцемёт позволяющий лечить людей на расстоянии.
#  productEntity: WeaponSyringeGun
#  cost:
#    CentCommCrystal: 4
#  categories:
#  - BSnanit
#  conditions:
#  - !type:ListingLimitedStockCondition
#   stock: 1

- type: listing
  id: CigPackBlackShop
  productEntity: CigPackBlack
  cost:
    CentCommCrystal: 1
  categories:
  - BSnanit

- type: listing
  id: InjectorWeakNanit'sShop
  productEntity: InjectorWeakNanits
  cost:
    CentCommCrystal: 4
  categories:
  - BSnanit

- type: listing
  id: CombatMedipenShop
  productEntity: CombatMedipen
  cost:
    CentCommCrystal: 2
  categories:
  - BSnanit

- type: listing
  id: MedkitCombatFilledShop
  description: Аптечка необходимая для лечения боевых ранений.
  productEntity: MedkitCombatFilled
  cost:
    CentCommCrystal: 2
  categories:
  - BSnanit

- type: listing
  id: OmnizineChemistryBottleShop
  name: Бутылочка омнизина
  description: Химичское вещество позволяющее вылечить большинство повреждений.
  productEntity: OmnizineChemistryBottle
  cost:
    CentCommCrystal: 3
  categories:
  - BSnanit

- type: listing
  id: PenCentcomShop
  productEntity: PenCentcom
  cost:
    CentCommCrystal: 1
  categories:
  - BSmore

- type: listing
  id: EncryptionKeyBinaryShop
  productEntity: EncryptionKeyBinary
  cost:
    CentCommCrystal: 2
  categories:
  - BSmore
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1

- type: listing
  id: FlashShop
  productEntity: Flash
  cost:
    CentCommCrystal: 1
  categories:
  - BSmore

- type: listing
  id: SpaceCash20000Shop
  description: 20000 кредитов для покупки разного снаряжения на станции.
  productEntity: SpaceCash20000
  cost:
    CentCommCrystal: 3
  categories:
  - BSmore
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1

- type: listing
  id: TargetClownShop
  productEntity: TargetClown
  cost:
    CentCommCrystal: 2
  categories:
  - BSmore
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1

- type: listing
  id: SoapNTShop
  productEntity: SoapNT
  cost:
    CentCommCrystal: 1
  categories:
  - BSengi

- type: listing
  id: ClothingBeltUtilityEngineeringShop
  description: Полный набор инструментов позволяющий разобрать что угодно.
  productEntity: ClothingBeltUtilityEngineering
  cost:
    CentCommCrystal: 2
  categories:
  - BSengi

- type: listing
  id: JawsOfLifeShop
  description: Комбинация лома и кусачек необходимая для вскрытия дверей и пожарных шлюзов.
  productEntity: JawsOfLife
  cost:
    CentCommCrystal: 2
  categories:
  - BSengi
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1

- type: listing
  id: ClothingBackpackDuffelSurgeryFilledShop
  productEntity: ClothingBackpackDuffelSurgeryFilled
  cost:
    CentCommCrystal: 4
  categories:
  - BSengi

- type: listing
  id: TrackingImplanterShop
  name: Импланты трекера
  productEntity: CrateTrackingImplants
  cost:
    CentCommCrystal: 2
  categories:
  - BSimp

- type: listing
  id: MindShieldImplanterShop
  name: Импланты защиты разума
  productEntity: CrateMindShieldImplants
  cost:
    CentCommCrystal: 2
  categories:
  - BSimp

- type: listing
  id: PersonalAIShop
  productEntity: PersonalAI
  cost:
    CentCommCrystal: 1
  categories:
  - BSsouz
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1

- type: listing
  id: BoxMREShop
  productEntity: BoxMRE
  cost:
    CentCommCrystal: 1
  categories:
  - BSmoremore

- type: listing
  id: ClothingNeckScarfStripedBlueShop
  productEntity: ClothingNeckScarfStripedBlue
  cost:
    CentCommCrystal: 1
  categories:
  - BSmoremore

- type: listing
  id: RevolverCapGunShop
  productEntity: RevolverCapGun
  cost:
    CentCommCrystal: 1
  categories:
  - BSmoremore
  conditions:
  - !type:ListingLimitedStockCondition
   stock: 1

- type: listing
  id: BalloonNTShop
  productEntity: BalloonNT
  cost:
    CentCommCrystal: 20
  categories:
  - BSmoremore

- type: listing
  id: ClothingHeadHatCatEarsshop
  productEntity: ClothingHeadHatCatEars
  cost:
    CentCommCrystal: 20
  categories:
  - BSmoremore
