#Комбинезон ЦСС
- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitCLEA
  name: Комбинезон ЦСС
  description: теперь в новой цветовой гамме!
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_uniform.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_uniform.rsi

#Шлем ЦСС
- type: entity
  parent: ClothingHeadBase
  id: ClothingHeadHelmetCLEA
  name: Шлем ЦСС
  description: им можно колоть орехи
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_Helmet.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_Helmet.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.90
        Slash: 0.90
        Piercing: 0.90
        Heat: 0.90
  - type: FlashImmunity
  - type: EyeProtection
    protectionTime: 5

#Кепка офицера ЦСС
- type: entity
  parent: ClothingHeadBase
  id: ClothingHeadBaseCapCLEA
  name: Кепка офицера ЦСС
  description: Повседневный головной убор ЦСС.
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_cap.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_cap.rsi

#Гарнитура-наушники ЦСС
- type: entity
  name: Гарнитура-наушники ЦСС
  parent: ClothingHeadsetAltCentCom
  id: CLEAHeadsetAlt
  description: Гарнитура, оснащенная подавляющими наушниками.
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_Headset.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_Headset.rsi

#Защитные очки ЦСС
- type: entity
  parent: [ClothingEyesGlassesSunglasses, ShowSecurityIcons]
  id: ClothingEyesGlassesCLEA
  description: Очки, защищающие глаза от яркого света.
  name: Защитные очки ЦСС
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_glasses.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_glasses.rsi
  - type: FlashImmunity
  - type: EyeProtection
    protectionTime: 5

#Боевые перчатки ЦСС
- type: entity
  parent: ClothingHandsGlovesColorBlack
  id: ClothingHandsGlovesCLEA
  name: Боевые перчатки ЦСС
  description: Тактический перчатки элитных солдат.
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_Gloves.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_Gloves.rsi
  - type: Insulated
  - type: Fiber
    fiberMaterial: fibers-insulative

#Противогаз ЦСС
- type: entity
  parent: ClothingMaskGas
  id: ClothingMaskCLEA
  name: Противогаз ЦСС
  description: не освежает дыхание
  components:
  - type: Item
    size: Tiny
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_mask.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_mask.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.95
        Slash: 0.95
        Piercing: 0.95
        Heat: 0.95
  - type: IngestionBlocker
  - type: IdentityBlocker
  - type: Tag
    tags:
    - HidesHair
  - type: FlashImmunity
  - type: EyeProtection
    protectionTime: 5

#РПС ЦСС
- type: entity
  parent: [ClothingBeltSecurityWebbing, ContentsExplosionResistanceBase]
  id: ClothingBeltMilitaryWebbingCLEA
  name: РПС ЦСС
  description: не сковывает движений!
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_Webbing.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_Webbing.rsi
  - type: ExplosionResistance
    damageCoefficient: 0.5

#Боевой Бронежилет ЦСС
- type: entity
  parent: ClothingOuterBaseMedium
  id: ClothingOuterArmorCLEA
  name: Боевой Бронежилет ЦСС
  description: Стандартный армейский бронежилет.
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_armor.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_armor.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.80
        Slash: 0.80
        Piercing: 0.80
        Heat: 0.80
  - type: ExplosionResistance
    damageCoefficient: 0.90
  - type: AllowSuitStorage

#Рюкзак ЦСС
- type: entity
  parent: ClothingBackpackSecurity
  id: ClothingMilitaryBackpackCLEA
  name: Рюкзак ЦСС
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_BackPack.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_BackPack.rsi
  - type: StorageFill
    contents:
    - id: BoxZiptie
    - id: CrowbarRed
    - id: DoubleEmergencyOxygenTankFilled

#ID карта ЦСС
- type: entity
  parent: IDCardStandard
  id: CLEAIDCard
  name: ID карта Солдата ЦСС
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/other/CLEA_IDcard.rsi
    layers:
    - state: silver
    - state: idCLEA
  - type: IdCard
    jobTitle: Солдат ЦСС
    jobIcon: JobIconCLEA
  - type: Item
    heldPrefix: silver
  - type: Access
    groups:
    - AllAccess
    tags:
    - CentralCommand

#ID карта офицера ЦСС
- type: entity
  parent: IDCardStandard
  id: CLEAOfficerIDCard
  name: ID карта Офицера ЦСС
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/other/CLEA_IDcard.rsi
    layers:
    - state: silver
    - state: idCLEA
  - type: IdCard
    jobTitle: Офицер ЦСС
    jobIcon: JobIconCLEA
  - type: Item
    heldPrefix: silver
  - type: Access
    groups:
    - AllAccess
    tags:
    - CentralCommand

#КПК солдата ЦСС
- type: entity
  parent: BasePDA
  id: CLEAPDA
  name: КПК Солдата ЦСС
  description: не такой робастный, как у отряда быстрого реагирования
  components:
  - type: Pda
    id: CLEAIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-CLEA
  - type: PdaBorderColor
    borderColor: "#4e4e56"
  - type: Icon
    state: pda-CLEA

#КПК офицера ЦСС
- type: entity
  parent: BasePDA
  id: CLEAOfficerPDA
  name: КПК Офицера ЦСС
  description: не такой робастный, как у отряда быстрого реагирования
  components:
  - type: Pda
    id: CLEAOfficerIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-CLEAOfficer
  - type: PdaBorderColor
    borderColor: "#4e4e56"
  - type: Icon
    state: pda-CLEAOfficer

#Скафандр ЦСС
- type: entity
  parent: ClothingOuterHardsuitSecurity
  id: ClothingOuterHardsuitCLEA
  name: Скафандр солдата ЦСС
  description: базовый боевой скафандр центральных силовых структур
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit.rsi
  - type: PressureProtection
    highPressureMultiplier: 0.5
    lowPressureMultiplier: 1000
  - type: ExplosionResistance
    damageCoefficient: 0.7
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.65
        Slash: 0.65
        Piercing: 0.65
        Caustic: 0.65
  - type: ClothingSpeedModifier
    walkModifier: 0.85
    sprintModifier: 0.85
  - type: HeldSpeedModifier
  - type: ToggleableClothing
    clothingPrototype: ClothingHeadHelmetHardsuitCLEA

- type: entity
  parent: ClothingHeadHardsuitBase
  id: ClothingHeadHelmetHardsuitCLEA
  name: Шлем скафандра солдата ЦСС
  description: таким шлемом можно колоть орехи
  components:
  - type: BreathMask
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit_helmet.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit_helmet.rsi
  - type: PressureProtection
    highPressureMultiplier: 0.3
    lowPressureMultiplier: 1000

#Скафандр офицера ЦСС
- type: entity
  parent: ClothingOuterHardsuitSecurity
  id: ClothingOuterHardsuitCLEAOfficer
  name: Скафандр офицера ЦСС
  description: базовый боевой скафандр центральных силовых структур
  components:
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit_Officer.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit_Officer.rsi
  - type: PressureProtection
    highPressureMultiplier: 0.5
    lowPressureMultiplier: 1000
  - type: ExplosionResistance
    damageCoefficient: 0.6
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.60
        Slash: 0.60
        Piercing: 0.60
        Caustic: 0.60
  - type: ClothingSpeedModifier
    walkModifier: 0.90
    sprintModifier: 0.90
  - type: HeldSpeedModifier
  - type: ToggleableClothing
    clothingPrototype: ClothingHeadHelmetHardsuitCLEAOfficer

- type: entity
  parent: ClothingHeadHardsuitBase
  id: ClothingHeadHelmetHardsuitCLEAOfficer
  name: Шлем скафандра офицера ЦСС
  description: таким шлемом можно колоть орехи
  components:
  - type: BreathMask
  - type: Sprite
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit_helmet_Officer.rsi
  - type: Clothing
    sprite: Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit_helmet_Officer.rsi
  - type: PressureProtection
    highPressureMultiplier: 0.3
    lowPressureMultiplier: 1000