#Роль
- type: job
  id: Brigmedic
  name: бригмедик
  description: Оказывайте медицинскую помощь заключенным и сотрудникам службы безопасности.
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000 #5 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 #2 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 #3 hrs # Corvax-RoleTime
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 3600 #1 hrs
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 3600 #1 hrs
  startingGear: BrigmedicGearADVENT
  icon: "JobIconBrigmedic"
  requireAdminNotify: true
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Medical
  - Maintenance
  - Cryogenics
  - External
  - Brig
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: playTimeTracker
  id: JobBrigmedic

#Гир
- type: startingGear
  id: BrigmedicGearADVENT
  equipment:
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    id: BrigmedicPDAADV
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltMedicalFilled
  storage:
    back:
    - Flash

#Карта
- type: entity
  parent: BrigmedicIDCard
  id: BrigmedicIDCardADV
  suffix: Adventure
  name: ID карта бригмедика
  components:
  - type: PresetIdCard
    job: Brigmedic

- type: entity
  parent: BrigmedicPDA
  id: BrigmedicPDAADV
  name: КПК бригмедика
  components:
  - type: Pda
    id: BrigmedicIDCardADV

#Спавнер
- type: entity
  id: SpawnPointBrigmedicAdven
  parent: SpawnPointJobBase
  name: brigmedic
  suffix: AdvRoles, AdvMapping
  components:
  - type: SpawnPoint
    job_id: Brigmedic
  - type: Sprite
    layers:
      - state: green
      - state: brigmedic
